# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59a93e974457d575c64b4b4d8baec340f2411a77710da53086df770ba020d7995813c94276dbed893d5e484b5f7b7b55ef2b8d297c23719940faee4afed4cef7

test:
  secret_key_base: ec7836bbe29535b2f619eb7042dc3658ae0bf0c471879e1785fb218639ba520c7154345d8ec9f1a6d4e21e4e74723446832e6b19d1f91c626ddafbc058ff3ef6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
