Source.create!(private_name: "cnn", public_name: "CNN", score: -5)
Source.create!(private_name: "the-huffington-post", public_name: "The Huffington Post", score: -3)
Source.create!(private_name: "the-wall-street-journal", public_name: "The Wall Street Journal", score: 4)
Source.create!(private_name: "the-new-york-times", public_name: "The New York Times", score: -2)
Source.create!(private_name: "usa-today", public_name: "USA Today", score: 1)
Source.create!(private_name: "google-news", public_name: "Google News", score: -1)
Source.create!(private_name: "bbc-news", public_name: "BBC News", score: -2)
Source.create!(private_name: "ars-technica", public_name: "Ars Technica", score: -1)
Source.create!(private_name: "associated-press", public_name: "AP", score: -1)
Source.create!(private_name: "bloomberg", public_name: "Bloomberg", score: 1)
Source.create!(private_name: "business-insider", public_name: "Business Insider", score: 1)
Source.create!(private_name: "buzzfeed", public_name: "Buzzfeed", score: -5)
Source.create!(private_name: "cnbc", public_name: "CNBC", score: -3)
Source.create!(private_name: "engadget", public_name: "Engadget", score: -1)
Source.create!(private_name: "financial-times", public_name: "Financial Times", score: 2)
Source.create!(private_name: "fortune", public_name: "Fortune", score: 1)
Source.create!(private_name: "independent", public_name: "Independent", score: 1)
Source.create!(private_name: "mashable", public_name: "Mashable", score: -2)
Source.create!(private_name: "mirror", public_name: "The Daily Mirror", score: 2)
Source.create!(private_name: "newsweek", public_name: "Newsweek", score: -3)
Source.create!(private_name: "polygon", public_name: "Polygon", score: -1)
Source.create!(private_name: "reuters", public_name: "Reuters", score: 1)
Source.create!(private_name: "techcrunch", public_name: "TechCrunch", score: -2)
Source.create!(private_name: "the-economist", public_name: "The Economist", score: 2)
Source.create!(private_name: "the-telegraph", public_name: "The Telegraph", score: 1)
Source.create!(private_name: "time", public_name: "TIME", score: -1)
Source.create!(private_name: "the-washington-post", public_name: "The Washington Post", score: -1)
Source.create!(private_name: "the-guardian-uk", public_name: "The Guardian", score: 1)
Source.create!(private_name: "recode", public_name: "Recode", score: -1)
Source.create!(private_name: "metro", public_name: "Metro", score: 2)
